# NumPy Assignment Solutions  

### This Jupyter Notebook contains solutions for Questions 1 to 20 from the NumPy Assignment.  

## 📂 File Structure for Better Readability:  
- **001_NumpyAssignment-1** → Solutions for Questions **1 to 20**  
- **002_NumpyAssignment-2** → Solutions for Questions **21 to 40**  
- **003_NumpyAssignment-3** → Solutions for Questions **41 to 60**  
- **004_NumpyAssignment-4** → Solutions for Questions **61 to 85**  

Each file is structured to ensure clarity and ease of navigation. 🚀  

In [1]:
import numpy as np

In [2]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
list=[1,2,3,4,5]
arr=np.array(list)
print(arr.dtype)  

int64


In [ ]:
# 2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)  # Yes , It's Datatype Is 'float64'...

float64


In [4]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3-4j, 5+6j], dtype=np.complex128)
print("Complex Array: ", arr)

Complex Array:  [1.+2.j 3.-4.j 5.+6.j]


In [7]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr=np.array([1,2,3,4,5])
arr=np.array(arr,dtype=np.float32)
print(arr.dtype)

float32


In [ ]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision
arr=np.array([1.2,2.3,3.4,4.5,5.6])
print(arr.dtype)

arr=np.array(arr,dtype=np.float32)
print(arr.dtype)

float64
float32


In [ ]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr=np.array([1,2,3,4,5])
print(array_attributes(arr))   

((5,), 5, dtype('int64'))


In [12]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    return arr.ndim

arr=np.array([1,2,3,4,5])
print(array_dimension(arr))

1


In [13]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total-size in bytes.
def item_size_info(arr):
    item_size = arr.itemsize  
    total_size = arr.nbytes   
    return item_size, total_size

arr=np.array([1,2,3,4,5])
print(item_size_info(arr))

(8, 40)


In [ ]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

arr=np.array([1,2,3,4,5])
print(array_strides(arr))

(8,)


In [16]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape ,arr.strides

arr=np.array([1,2,3,4,5])
print(shape_stride_relationship(arr))

((5,), (8,))


In [17]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)  

print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [18]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(m,n):
    return np.ones((m,n))

print(create_ones_matrix(2,3))

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

print(generate_range_array(1,10,2))

[1 3 5 7 9]


In [20]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop`(inclusive).

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(1.0, 5.0, 5))  

[1. 2. 3. 4. 5.]


In [23]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(2))

[[1. 0.]
 [0. 1.]]


In [25]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def listToArray(list):
    return np.array(list)

print(listToArray([1,2,3,4,5]))  

[1 2 3 4 5]


In [ ]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
# Shallow Copy Is Been Done Here 

arr = np.array([10, 20, 30, 40])
view_arr = arr.view()

view_arr[0] = 99
print("Original Array:", arr)  
print("View Array:", view_arr)

Original Array: [99 20 30 40]
View Array: [99 20 30 40]


In [28]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Concatenated along axis 0:", concatenate_arrays(arr1, arr2, axis=0))
print("Concatenated along axis 1:", concatenate_arrays(arr1, arr2, axis=1))

Concatenated along axis 0: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1: [[1 2 5 6]
 [3 4 7 8]]


In [29]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
arr1 = np.array([[1, 2], [3, 4]])    # Shape: (2, 2)
arr2 = np.array([[5], [6]])          # Shape: (2, 1)

print("Concatenated Array:", np.concatenate((arr1, arr2), axis=1))

Concatenated Array: [[1 2 5]
 [3 4 6]]


In [30]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

import numpy as np

def vertical_stack(arr_list):
    return np.vstack(arr_list)

arr1 = np.array([[1, 2], [3, 4]])  # Shape: (2,2)
arr2 = np.array([[5, 6]])          # Shape: (1,2)
arr3 = np.array([[7, 8]])          # Shape: (1,2)

result = vertical_stack([arr1, arr2, arr3])
print("Vertically Stacked Array:\n", result)


Vertically Stacked Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
