# NumPy Assignment Solutions  

### This Jupyter Notebook contains solutions for Questions 21 to 40 from the NumPy Assignment.  

## 📂 File Structure for Better Readability:  
- **001_NumpyAssignment-1** → Solutions for Questions **1 to 20**  
- **002_NumpyAssignment-2** → Solutions for Questions **21 to 40**  
- **003_NumpyAssignment-3** → Solutions for Questions **41 to 60**  
- **004_NumpyAssignment-4** → Solutions for Questions **61 to 85**  

Each file is structured to ensure clarity and ease of navigation. 🚀  

In [1]:
import numpy as np

In [2]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create_integer_array(start, stop, step):
    return np.arange(start, stop + 1, step)

print(create_integer_array(1, 10, 2))  

[1 3 5 7 9]


In [3]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def generate_equally_spaced():
    return np.linspace(0, 1, 10)

print(generate_equally_spaced())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [4]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def generate_log_spaced():
    return np.logspace(0, 3, 5)

print(generate_log_spaced())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [5]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100.
import pandas as pd

def create_dataframe():
    return pd.DataFrame(np.random.randint(1, 101, (5, 3)))

print(create_dataframe())


     0   1   2
0   12  33  73
1   34  30  16
2   79   7  95
3  100  20  76
4   43  72  90


In [6]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
# with zeros. Use NumPy operations within the Pandas DataFrame.
import pandas as pd

def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

data = pd.DataFrame({'A': [1, -2, 3, -4, 5], 'B': [-10, 20, -30, 40, -50]})
print(replace_negatives(data, 'A'))


   A   B
0  1 -10
1  0  20
2  3 -30
3  0  40
4  5 -50


In [8]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [9]:
#  27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[1, 2])  

6


In [11]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]
print(result)

[ 8 10  7]


In [12]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])  

[3 4 5 6]


In [20]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr_2d[0:2, 1:3])

[[2 3]
 [5 6]]


In [ ]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(arr, indices):
    return arr[indices[:, 0], indices[:, 1]]

arr_2d = np.array([[10, 20, 30], 
                   [40, 50, 60], 
                   [70, 80, 90]])

indices = np.array([[0, 2], [1, 1], [2, 0]])

print(extract_elements(arr_2d, indices))


[30 50 70]


In [22]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

arr_1d = np.array([10, 25, 3, 45, 7, 18])
threshold = 15

print(filter_greater_than(arr_1d, threshold))


[25 45 18]


In [23]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_from_3d(arr, x_indices, y_indices, z_indices):
    return arr[x_indices, y_indices, z_indices]

arr_3d = np.arange(27).reshape(3, 3, 3)

x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 0, 2])
z_indices = np.array([2, 1, 0])

print(extract_from_3d(arr_3d, x_indices, y_indices, z_indices))


[ 5 10 24]


In [24]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def filter_with_conditions(arr, cond1, cond2):
    return arr[(arr > cond1) & (arr < cond2)]

arr_1d = np.array([5, 12, 18, 25, 30, 40])
cond1 = 10
cond2 = 30

print(filter_with_conditions(arr_1d, cond1, cond2))


[12 18 25]


In [26]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract(arr_2d, index_arr):
    for i in range(len(index_arr)):  
        print(arr_2d[index_arr[i, 0], index_arr[i, 1]], end=" ")

arr_2d = np.array([[10, 20, 30], 
                   [40, 50, 60], 
                   [70, 80, 90]])

indices = np.array([[0, 2], [1, 1], [2, 0]])
extract(arr_2d, indices)

30 50 70 

In [ ]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
def add_scalar(arr):
    return arr + 5

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(add_scalar(arr))

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [28]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
# corresponding element in arr1 using NumPy broadcasting.

def multiply_broadcast(arr1, arr2):
    return arr2 * arr1.T

arr1 = np.array([[2, 3, 4]])  
arr2 = np.array([[1, 2, 3, 4],  
                 [5, 6, 7, 8],  
                 [9, 10, 11, 12]])

print(multiply_broadcast(arr1, arr2))

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [29]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting
def add_broadcast(arr1, arr2):
    return arr2 + arr1

arr1 = np.array([[1, 2, 3, 4]])  
arr2 = np.array([[10, 20, 30],  
                 [40, 50, 60],  
                 [70, 80, 90],  
                 [100, 110, 120]])

print(add_broadcast(arr1.T, arr2))

[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [30]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
def add_broadcast(arr1, arr2):
    return arr1 + arr2

arr1 = np.array([[1],  
                 [2],  
                 [3]])

arr2 = np.array([[10, 20, 30]])

print(add_broadcast(arr1, arr2))

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [31]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
# broadcasting. Handle the shape incompatibility.
def multiply_broadcast(arr1, arr2):
    if arr1.shape[1] != arr2.shape[1]:
        raise ValueError("Shapes are incompatible for broadcasting")
    return arr1 * arr2[:, :arr1.shape[1]]

arr1 = np.array([[1, 2, 3],  
                 [4, 5, 6]])

arr2 = np.array([[10, 20],  
                 [30, 40]])

try:
    print(multiply_broadcast(arr1, arr2))
except ValueError as e:
    print(e)

Shapes are incompatible for broadcasting
